### ISSUE TITLE
Issue in encoding string-types

### ISSUE THREAD

**Issue by DanielWolf** [mikerabat/DelphiCBOR#1]
when encoding longer structures, the length-bytes must be in reversed order. this is implemented correctly for arrays, maps etc. but not for string-types.
the calls to "RevertByteOrder(@dwLen, sizeof(dwLen));" are missing from the routines "TCborUtf8String.CBOREncode and "TCborByteString.CBOREncode". (must be included twice in each class, for "word" and "longword")

**Comment by mikerabat** [comment]
You are right... fixed it already... thanks for pointing that out!
